### ISSUE TITLE
Event fire at initialisation with no voltage on pin

### ISSUE THREAD

**Issue by sheepchen** [gusmanb/BCM2835Managed#2]
If you add a eventcall it fires even when the pin is constandly low. I monitored the pin with an ossiloscope.
(C# code below)

setup
--------------
Raspberry PI 2 Model B v1.1
OS: raspberryan, all setup (other GPIO-progs have no problem)
Switch between pin 25 (ground) and 15 (GPIO22).

on raspberry:
--------------
root /work/testprgs/test2 > dotnet test2.dll
Signal detected on pin RPI_GPIO_P1_15

on ossiloscope
--------------
the voltage between pin 25 (ground) and 15 (GPIO22) is constandly zero.
It rises only if I push the switch and falls instandly by releasing (Pulldown in pinsetup). In the case when I press the switch, the event triggers as it should.

examplecode:
--------------
```
using HighLevelObjects;
using System;

namespace test2
{
    class Program
    {
        static void Main(string[] args)
        {
            var p = new Program();
            p.main();
        }


        void main()
        {
            BCM2835.BCM2835Managed.bcm2835_init();

            GPIOPin inp = new GPIOPin(BCM2835.BCM2835Managed.RPiGPIOPin.RPI_V2_GPIO_P1_15, GPIOFunction.Input, GPIOPullControl.PullDown);
            inp.Edge = Edge.Rising;
            inp.EventDetected += Inp_EventDetected;


            System.Threading.Thread.Sleep(1000000);

            void Inp_EventDetected(object sender, SignalEventArgs e)
            {
                Console.WriteLine("Signal detected on pin " + e.Pin);
            }
        }


    }
}
```

**Comment by gusmanb** [comment]
Thanks for the report. I will try to check it next week. 

Per your report it seems like there is a change event cached by the system when you add the detector and that rises the event when you attach the handler.

I will try to drain the pin stastus file before starting to send events, that will correct the problem.

Also, can you check the value of e.Signal? I think that first event will be false instead of true (false means falling edge), if that's the case then as a workaround until I revise the code would be to discard any event that does not match the rising edge.

Cheers.

**Comment by sheepchen** [comment]
sorry, i reprogrammed my wrapper to another library that better suits my requirements. But the signalvalue should be false at this point.
I initialize the BCM before, but I noticed that the init-procedure of the BCM-chip is messy on the hardwarelevel. not all registers are nulled. So the best way is to null the register at the registration of an event. 
bcm2835_gpio_set_eds()
